<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Are vehicles in Chicago susceptible targets of crime?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Chicago_motor_theft_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Chicago_motor_theft_report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Chicago_motor_theft_report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Chicago_motor_theft_report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Chicago_motor_theft_report_files/libs/quarto-html/popper.min.js"></script>
<script src="Chicago_motor_theft_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Chicago_motor_theft_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Chicago_motor_theft_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Chicago_motor_theft_report_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Chicago_motor_theft_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Chicago_motor_theft_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Chicago_motor_theft_report_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Are vehicles in Chicago susceptible targets of crime?</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This report outlines the source code that was used to determine the susceptibility of vehicles in Chicago.</p>
<p>The report is broken down into 4 smaller research questions each with their own analyses.</p>
<ol type="1">
<li><strong>When are the vehicles stolen?</strong></li>
<li><strong>How many vehicles are stolen?</strong></li>
<li><strong>Which communities will have a vehicle stolen from it?</strong></li>
<li><strong>Do communities have the different arrest rates for vehicle thefts?</strong></li>
</ol>
<section id="when-are-vehicles-stolen" class="level2">
<h2 class="anchored" data-anchor-id="when-are-vehicles-stolen">1. When are vehicles stolen?</h2>
<p>We will explore the subquestion: What is the probability that a vehicle theft in Chicago occurs at night? Define ‘night’ in this question as between 6pm and 6am.</p>
<p>Read in the Chicago crime dataset. The data has already been filtered to only include vehicle thefts in 2026, since that is our subject of interest. Each row has a unique ID and case number, and the rest of the columns contain other details about the crime.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/chicago_vehicle_theft_crimes_2026.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># add a column converting Date to DateTime</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DateTime =</span> <span class="fu">strptime</span>(Date, <span class="at">format =</span> <span class="st">"%m/%d/%Y %I:%M:%S %p"</span>))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df,<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID Case.Number                   Date                  Block IUCR
1 14118381    JK158640 02/22/2026 12:00:00 AM      063XX S MOZART ST  920
2 14118195    JK158333 02/22/2026 12:00:00 AM 051XX N CALIFORNIA AVE  910
3 14118379    JK158602 02/21/2026 11:30:00 PM    006XX N FRANKLIN ST  910
         Primary.Type          Description Location.Description Arrest Domestic
1 MOTOR VEHICLE THEFT ATTEMPT - AUTOMOBILE               STREET  false    false
2 MOTOR VEHICLE THEFT           AUTOMOBILE               STREET  false    false
3 MOTOR VEHICLE THEFT           AUTOMOBILE               STREET  false    false
  Beat District Ward Community.Area FBI.Code X.Coordinate Y.Coordinate Year
1  823        8   15             66        7      1158470      1862494 2026
2 2031       20   40              4        7      1156765      1934163 2026
3 1831       18   42              8        7      1174220      1904299 2026
              Updated.On Latitude Longitude                      Location
1 03/01/2026 04:09:12 PM 41.77842 -87.69459  (41.778420097, -87.69459002)
2 03/01/2026 04:09:12 PM 41.97512 -87.69890 (41.975121537, -87.698898525)
3 03/01/2026 04:09:12 PM 41.89280 -87.63560 (41.892800977, -87.635604802)
             DateTime
1 2026-02-22 00:00:00
2 2026-02-22 00:00:00
3 2026-02-21 23:30:00</code></pre>
</div>
</div>
<p><strong>Exploring the data</strong></p>
<p>Let’s take a preliminary look at the data to get an idea of what we’re working with. What does the basic distribution of vehicle thefts look like across the hours of the day?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hour =</span> <span class="fu">hour</span>(DateTime),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">period =</span> <span class="fu">ifelse</span>(hour <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">|</span> hour <span class="sc">&lt;</span> <span class="dv">6</span>, <span class="st">"Night"</span>, <span class="st">"Day"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(hour, period) <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(hour), <span class="at">y =</span> n, <span class="at">fill =</span> period)) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()<span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"2026 Vehicle Thefts by Hour of Day"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Hour of Day"</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that car thefts generally tend to be more common at night, between 6pm and up until 3am. Indeed, the volume of the blue columns outweighs the pink columns. So we know <span class="math inline">\(\pi\)</span> will likely be greater than 0.5. But by how much?</p>
<p><strong>Building a prior</strong></p>
<p>To build a prior, we look at 2024 vehicle theft data as reported by the FBI National Incident-Based Reporting System, which reported that out of approximately 750,000 vehicle thefts that year, around 52.4% occurred between 6pm and 6am.</p>
<p>We assign a Beta(104, 96) prior to <span class="math inline">\(\pi\)</span>, the probability a vehicle theft occurs at night, putting the mean at 0.52 and most values between 0.45 and 0.59.</p>
<p>A Beta prior is a good choice for this data because it is defined on 0 to 1, the same domain as a probability. The Beta distribution is also conjugate to the Binomial likelihood, so we will be able to produce an informative Beta posterior given data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize_beta</span>(<span class="dv">104</span>, <span class="dv">96</span>) <span class="co"># mean at 0.52, mode at 0.52</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mean     mode         var         sd
1 0.52 0.520202 0.001241791 0.03523906</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="dv">104</span>, <span class="dv">96</span>) <span class="co"># 95% credible interval between 0.45 and 0.59</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4508169 0.5888041</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_beta</span>(<span class="dv">104</span>, <span class="dv">96</span>) <span class="co"># visualize the distribution</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Likelihood</strong></p>
<p>The Binomial model for the number of vehicle thefts that took place at night is <span class="math inline">\(Y|\pi \sim Bin(2369, \pi)\)</span>. n=2369 because that is the number of rows in our dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2369</code></pre>
</div>
</div>
<p>From our data, we observe that Y=1371 of vehicle thefts took place at night.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>count_night <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">hour</span>(DateTime) <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">|</span> <span class="fu">hour</span>(DateTime) <span class="sc">&lt;</span> <span class="dv">6</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>count_night</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1371</code></pre>
</div>
</div>
<p>Our likelihood function is <span class="math display">\[L(\pi \mid y=1371) = \pi^{1371}(1-\pi)^{2369-1371}\]</span></p>
<p><strong>Derive the posterior</strong></p>
<p>The Beta posterior distribution of <span class="math inline">\(\pi\)</span> after having observed the data is</p>
<p><span class="math display">\[\pi | y \sim Beta (\alpha + y, \beta + n - y) \]</span> <span class="math display">\[\pi | y \sim Beta(104 + 1371, 96 + 2369 - 1371) \]</span> <span class="math display">\[\pi | y \sim Beta(1475, 1094) \]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_beta</span>(<span class="dv">1475</span>, <span class="dv">1094</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Our posterior distribution has a lot less variance than our prior, and a higher mean and mode.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize_beta</span>(<span class="dv">1475</span>, <span class="dv">1094</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       mean      mode          var          sd
1 0.5741534 0.5742111 9.513668e-05 0.009753804</code></pre>
</div>
</div>
<p>The mean and mode of the posterior are around 0.57.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_beta_binomial</span>(<span class="at">alpha=</span><span class="dv">104</span>, <span class="at">beta=</span><span class="dv">96</span>, <span class="at">y=</span><span class="dv">1371</span>, <span class="at">n=</span><span class="dv">2369</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Because of our large sample size, the posterior is “weighted” more toward the likelihood. In our data we observed a greater <span class="math inline">\(\pi\)</span> compared with our prior, so the mean of the posterior is pulled in the direction of the data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize_beta_binomial</span>(<span class="at">alpha=</span><span class="dv">104</span>, <span class="at">beta=</span><span class="dv">96</span>, <span class="at">y=</span><span class="dv">1371</span>, <span class="at">n=</span><span class="dv">2369</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      model alpha beta      mean      mode          var          sd
1     prior   104   96 0.5200000 0.5202020 1.241791e-03 0.035239056
2 posterior  1475 1094 0.5741534 0.5742111 9.513668e-05 0.009753804</code></pre>
</div>
</div>
<p>We confirm that our posterior has a higher mean and mode than our prior. So based on the data we observed, the probability that a vehicle theft occurs at night is higher than we originally thought, around 0.57 compared with 0.52.</p>
<p><strong>Grid Approximation</strong></p>
<p>Let’s approximate the posterior using grid approximation. First split the continuum of possible <span class="math inline">\(\pi\)</span> values onto a finite grid of 101 values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>grid_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pi_grid =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fl">0.50</span>, <span class="at">to =</span> <span class="fl">0.61</span>, <span class="at">length =</span> <span class="dv">101</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Encode the Beta(104, 96) prior and Binomial(2369, <span class="math inline">\(\pi\)</span>) likelihood with Y=1371 at each <span class="math inline">\(\pi\)</span> in pi_grid.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>grid_data <span class="ot">&lt;-</span> grid_data <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prior =</span> <span class="fu">dbeta</span>(pi_grid, <span class="dv">104</span>, <span class="dv">96</span>),</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood =</span> <span class="fu">dbinom</span>(<span class="dv">1371</span>,<span class="dv">2369</span>, pi_grid))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now approximate the posterior.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>grid_data <span class="ot">&lt;-</span> grid_data <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">unnormalized =</span> likelihood <span class="sc">*</span> prior,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">posterior =</span> unnormalized <span class="sc">/</span> <span class="fu">sum</span>(unnormalized))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Plot the discretized posterior pdf.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(grid_data, <span class="fu">aes</span>(<span class="at">x =</span> pi_grid, <span class="at">y =</span> posterior)) <span class="sc">+</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> pi_grid, <span class="at">xend =</span> pi_grid, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">yend =</span> posterior))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now, let’s sample from the discretized posterior.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">84735</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>post_sample <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(grid_data, <span class="at">size =</span> <span class="dv">10000</span>, </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">weight =</span> posterior, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(post_sample<span class="sc">$</span>pi_grid, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2.5%  97.5% 
0.5550 0.5935 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">84735</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(post_sample, <span class="fu">aes</span>(<span class="at">x =</span> pi_grid)) <span class="sc">+</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">bins=</span><span class="dv">34</span>) <span class="sc">+</span> </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dbeta, <span class="at">args =</span> <span class="fu">list</span>(<span class="dv">1475</span>, <span class="dv">1094</span>)) <span class="sc">+</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lims</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.61</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This sample aligns much better with the actual posterior pdf, and we once again conclude that the probability that a vehicle theft occurs at night is around 0.57, with a credible interval between 0.56 and 0.59.</p>
<p><strong>Comparing Weekends and Weekdays</strong></p>
<p>Since people’s activities tend to be different on weekdays and weekdays, let’s compare the distribution of vehicle thefts by those two groups. We use the beta (104, 96) prior.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find total thefts</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>weekend_count <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">wday</span>(DateTime) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">7</span>)) <span class="sc">%&gt;%</span>   <span class="co"># Sunday = 1, Saturday = 7</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>()</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>weekday_count <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">wday</span>(DateTime) <span class="sc">%in%</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>) <span class="sc">%&gt;%</span>   <span class="co"># Monday–Friday</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>()</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>weekend_count</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 734</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>weekday_count</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1635</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>weekend_night_count <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    (<span class="fu">hour</span>(DateTime) <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">|</span> <span class="fu">hour</span>(DateTime) <span class="sc">&lt;</span> <span class="dv">6</span>) <span class="sc">&amp;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">wday</span>(DateTime) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">7</span>)   <span class="co"># Sunday = 1, Saturday = 7</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>()</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>weekday_night_count <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    (<span class="fu">hour</span>(DateTime) <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">|</span> <span class="fu">hour</span>(DateTime) <span class="sc">&lt;</span> <span class="dv">6</span>) <span class="sc">&amp;</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">wday</span>(DateTime) <span class="sc">%in%</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>   <span class="co"># Monday = 2 ... Friday = 6</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>()</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>weekend_night_count</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 436</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>weekday_night_count</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 935</code></pre>
</div>
</div>
<p>We observe that 935 out of 1635 weekday vehicle thefts took place at night. 436 out of 734 weekend vehicle thefts took place at night</p>
<p>Update our priors:</p>
<p><span class="math display">\[\pi | y \sim Beta (\alpha + y, \beta + n - y) \]</span> <span class="math display">\[\pi_{weekday} | y_{weekday} \sim Beta (104 + 935, 96 + 1635 - 935) \]</span> <span class="math display">\[\pi_{weekend} | y_{weekend} \sim Beta (104 + 436, 96 + 734 - 436) \]</span> <span class="math display">\[\pi_{weekday} | y_{weekday} \sim Beta (1039, 796) \]</span> <span class="math display">\[\pi_{weekend} | y_{weekend} \sim Beta (540, 394) \]</span> Plot both posteriors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dbeta, <span class="at">args =</span> <span class="fu">list</span>(<span class="dv">1039</span>, <span class="dv">796</span>),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                <span class="fu">aes</span>(<span class="at">color =</span> <span class="st">"Weekday"</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dbeta, <span class="at">args =</span> <span class="fu">list</span>(<span class="dv">540</span>, <span class="dv">394</span>),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                <span class="fu">aes</span>(<span class="at">color =</span> <span class="st">"Weekend"</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Posterior Distributions"</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">expression</span>(pi),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Group"</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fl">0.5</span>, <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Find credible intervals and means:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>summary_weekday <span class="ot">&lt;-</span> <span class="fu">summarize_beta</span>(<span class="dv">1039</span>, <span class="dv">796</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>summary_weekday</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       mean      mode          var         sd
1 0.5662125 0.5662848 0.0001337777 0.01156623</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>summary_weekend <span class="ot">&lt;-</span> <span class="fu">summarize_beta</span>(<span class="dv">540</span>, <span class="dv">394</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>summary_weekend</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       mean      mode          var         sd
1 0.5781585 0.5783262 0.0002608463 0.01615074</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>interval_weekday <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="dv">1039</span>, <span class="dv">796</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>interval_weekday</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5434775 0.5888109</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>interval_weekend <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="dv">540</span>, <span class="dv">394</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>interval_weekend</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5463525 0.6096473</code></pre>
</div>
</div>
<p><strong>Vehicles are slightly stolen more at night</strong></p>
<p>The posterior means indicate that nighttime vehicle thefts are slightly more likely on weekends (0.578) than on weekdays (0.566). However, the difference is small so while there may be a slight increase in risk on weekends, it is not a dramatic shift. The credible intervals also have significant overlap, so we can infer that the difference is not significant.</p>
<p>Informative results on the distribution of times of vehicle theft could potentially help people protect their personal vehicles by being wary of dangerous times to leave vehicles unlocked or out. Results could also help law enforcement enforce regulations to limit vehicle theft crimes, such as increasing street lighting at especially vulnerable times of day.</p>
<p>With more resources and time, I would like to conduct a deeper analysis of vehicle theft times with 2 time categories, perhaps hour-to-hour or between months. A limitation of my analysis it does not provide detailed insight outside of the proportion of vehicles stolen between 6am and 6pm and outside of that period.</p>
</section>
<section id="how-many-vehicles-will-be-stolen-in-chicago" class="level2">
<h2 class="anchored" data-anchor-id="how-many-vehicles-will-be-stolen-in-chicago">2. How many vehicles will be stolen in Chicago?</h2>
<p>In this section we will break down our statistical modelling for determining the number of stolen vehicles in Chicago for a new day.</p>
<p><strong>Exploring daily theft counts</strong></p>
<p>First we read the data set containing all currently reported vehicle thefts since the start of the 2026 year.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/chicago_vehicle_theft_crimes_2026.csv"</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co"># mdy_hms handles the string formatting "mm/dd/yyyy hh:mm:ss AM" automatically</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">mdy_hms</span>(df<span class="sc">$</span>Date)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the date to a numeric date since the start of the dataset</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>day_numeric <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(df<span class="sc">$</span>Date, <span class="fu">min</span>(df<span class="sc">$</span>Date), <span class="at">units =</span> <span class="st">"days"</span>))</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the numeric dates to discrete numbers </span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the incomplete current day</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">day_n =</span> <span class="fu">floor</span>(day_numeric)) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(day_n <span class="sc">!=</span> <span class="dv">52</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then grouping the reports by day and counting them, allows us to create a visualization to judge for any noticeable trends to model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate the counts of reported theft cases</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>daily_counts <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(day_n) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">theft_count =</span> <span class="fu">n</span>())</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the counts over days to looks for correlation</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(daily_counts, <span class="fu">aes</span>(<span class="at">x =</span> day_n, <span class="at">y =</span> theft_count)) <span class="sc">+</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span>  <span class="co"># Line shows the trend</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"darkblue"</span>) <span class="sc">+</span>  <span class="co"># Points show individual days</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Frequency of Vehicle Thefts"</span>,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Day Number"</span>,</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count of Thefts"</span>) <span class="sc">+</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Generally from the plot there is no specific trend from day-to-day which makes using an independence assumption more plausible.</p>
<p>Plotting the histograms of the reported numbers will show if mostly the numbers are centered around a similar value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Treating all days as independent events we can construct a density plot</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(daily_counts, <span class="fu">aes</span>(<span class="at">x =</span> theft_count)) <span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">binwidth =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Daily Theft Counts"</span>,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Number of Thefts per Day"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Counts"</span>) <span class="sc">+</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looking at the plot there is relatively high variance in the daily reported number of stolen vehicles in Chicago, however the number is generally centered around the 40-50 range, indicating that on average days have similar numbers of cars stolen.</p>
<p><strong>Statistical Model</strong></p>
<p>To model these counts we propose discrete random variables that range from 0 to infinity, which are independent and have the same mean. One type of random variable that can model these conditions is the Poisson random variable</p>
<p><span class="math display">\[\text{Let } Y_i\text{ represent the number of car thefts in on a day }i:\]</span></p>
<p><span class="math display">\[Y_i|\lambda \sim Poisson(\lambda)\]</span></p>
<p>Furthermore the rate of the Poisson random variable can be modeled as a Gamma random variable.</p>
<p><span class="math display">\[ \text{Let }\lambda \text{ represent the daily car theft rate}: \]</span></p>
<p><span class="math display">\[\lambda \sim Gamma(\alpha, \beta)\]</span></p>
<p><strong>Defining a Prior</strong></p>
<p>From research into priors the annual car theft rate in Chicago is 8.25 for every 1000 people. Given that Chicago has a population of around 2.72 million, that leads to 22440 total stolen cars per year in Chicago! (Insurance Information Institute)</p>
<p>Since we are using the independent and identically distributed assumption for the car theft rate in Chicago, we expect that the expected rate should be close to one 365th of the annual rate, which leads to a rate of 61.44.</p>
<p>For the variance of the rate, the monthly 5 year counts range from 630 to 3186 which translates into an average daily rate range of 21 to 106 and since each month in a 5 year range accounts for one 60th of the data, I suggest that choosing a distribution that has tail probabilities around 0.0166, for either or possibly both tails (City of Chicago). However a Gamma distribution is not flexible enough to model all three constraints simultaneously so I decided to only use the left tail probability assumption. In other words the 0.0166th quantile of the prior Gamma distribution should be 21.</p>
<p><span class="math display">\[\text{From our assumption that the average rate should be 61.44: }\]</span></p>
<p><span class="math display">\[\text{E}(\lambda) = \frac{\alpha}{\beta}= 61.44 \]</span></p>
<p><span class="math display">\[\beta= \frac{\alpha}{61.44}\]</span></p>
<p><span class="math display">\[ \text{From the assumption about the 0.0166th quantile being 21:} \]</span> <span class="math display">\[ \text{P}(\lambda \le 21) = 0.0166 \]</span></p>
<p><span class="math display">\[ \text{Substituting the CDF of a Gamma distribution:} \]</span></p>
<p><span class="math display">\[ \text{P}(\lambda \le x) = F(x; \alpha, \beta) =\int_{0}^{x} \frac{\beta^\alpha}{\Gamma(\alpha)} t^{\alpha-1} e^{-\beta t} \, dt =   \frac{\gamma(\alpha, \beta x)}{\Gamma(\alpha)} \]</span></p>
<p><span class="math display">\[ \text{Substituting the contraint from the expectation of a Gamma distribution:} \]</span></p>
<p><span class="math display">\[ \text{P}(\lambda \le 21) =\frac{\gamma(\alpha, \frac{21}{61.44}\alpha)}{\Gamma(\alpha)} = 0.0166\]</span></p>
<p><span class="math display">\[ \text{Analytically solving this is difficult so we computationally solve the unique solution for }\alpha :\]</span></p>
<p><span class="math display">\[ \text{P}(\lambda \le 21) = F(21,\alpha,\frac{\alpha}{61.44}) =  \text{pgamma}(21, \alpha,\frac{\alpha}{61.44}) = 0.0166 \]</span></p>
<p><span class="math display">\[ \text{Equivalently solving the single root of the funtion } g(\alpha): \]</span></p>
<p><span class="math display">\[  g(\alpha) = \text{pgamma}(21, \alpha,\frac{\alpha}{61.44}) - 0.0166= 0 \]</span></p>
<p>In R we can use the uniroot function to computationally solve the root for us:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Targets for gamma</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>target_mean <span class="ot">&lt;-</span> <span class="fl">61.44</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>target_tail_v <span class="ot">&lt;-</span> <span class="dv">21</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>target_tail_p <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">60</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining g(alpha)</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="cf">function</span>(alpha) {</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  beta <span class="ot">&lt;-</span> alpha <span class="sc">/</span> target_mean</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  tail_p <span class="ot">&lt;-</span> <span class="fu">pgamma</span>(target_tail_v, <span class="at">shape =</span> alpha, <span class="at">rate =</span> beta)</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(tail_p <span class="sc">-</span> target_tail_p)</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Solving the root of g</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>solution <span class="ot">&lt;-</span> <span class="fu">uniroot</span>(g, <span class="at">lower =</span> <span class="fl">0.01</span>, <span class="at">upper =</span> <span class="dv">100</span>)</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Substituting in the values for alpha and beta</span></span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>prior_alpha <span class="ot">&lt;-</span> solution<span class="sc">$</span>root</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>prior_beta <span class="ot">&lt;-</span> prior_alpha <span class="sc">/</span> target_mean</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Alpha:"</span>, <span class="fu">round</span>(prior_alpha, <span class="dv">4</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Alpha: 6.2116"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Beta:"</span>, <span class="fu">round</span>(prior_beta, <span class="dv">4</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Beta: 0.1011"</code></pre>
</div>
</div>
<p>Visualizing the constructed prior:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_gamma</span>(prior_alpha, prior_beta)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Checking our initial constraint of a mean rate of 61.44</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the mean of the distribution</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize_gamma</span>(prior_alpha,prior_beta)<span class="sc">$</span>mean</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 61.44</code></pre>
</div>
</div>
<p>and a high enough variance to make rates with smaller than the minimum average rates to not account for more than 0.0166 probability.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the quantiles of the minimum and maximum average rates in the past 5 years</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pgamma</span>(<span class="fu">c</span>(<span class="dv">21</span>,<span class="dv">106</span>),prior_alpha,prior_beta)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0166669 0.9476544</code></pre>
</div>
</div>
<p>Notice that this prior has constrained lower rates more than higher rates, but could have been reversed if there is more belief that rates that are higher than the maximum rate in the past 5 years should be less likely.</p>
<p><strong>Gamma-Poisson conjugacy</strong></p>
<p>Using a gamma-poisson model allows us to make use of a conjugate prior:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>total <span class="ot">=</span> <span class="fu">sum</span>(daily_counts<span class="sc">$</span>theft_count)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>days <span class="ot">=</span> <span class="fu">length</span>(daily_counts<span class="sc">$</span>day_n)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_gamma_poisson</span>(prior_alpha,prior_beta, total, days)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>resulting in the following posterior:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> prior_alpha <span class="sc">+</span> total</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> prior_beta <span class="sc">+</span> days</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_gamma</span>(alpha, beta)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize_gamma_poisson</span>(prior_alpha, prior_beta, total, days)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      model       shape       rate     mean     mode         var         sd
1     prior    6.211625  0.1011007 61.44000 51.54887 607.7111253 24.6517976
2 posterior 2373.211625 52.1011007 45.55012 45.53093   0.8742642  0.9350209</code></pre>
</div>
</div>
<p>Using this we can construct a 95% credible interval for the mean rate for tomorrows car theft rate</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qgamma</span>(<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>), alpha, beta)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 43.73576 47.40084</code></pre>
</div>
</div>
<p><strong>Posterior Prediction</strong></p>
<p>We can also simulate the actual number stolen tomorrow and construct the predictive interval</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">84735</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 500,000 potential average theft rates</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>n_sims <span class="ot">&lt;-</span> <span class="dv">500000</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>lambda_sims <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(n_sims, <span class="at">shape =</span> alpha, <span class="at">rate =</span> beta)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="co"># For each lambda, simulate a number of thefts</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>predictive_thefts <span class="ot">&lt;-</span> <span class="fu">rpois</span>(n_sims, <span class="at">lambda =</span> lambda_sims)</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(predictive_thefts, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2.5% 97.5% 
   33    59 </code></pre>
</div>
</div>
<p>With our assumptions, there is a 95% probability that the number of cars stolen tomorrow will be between 33 and 59 inclusive.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>predictive_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">thefts =</span> predictive_thefts)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(predictive_df, <span class="fu">aes</span>(<span class="at">x =</span> thefts)) <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(count <span class="sc">/</span> <span class="fu">sum</span>(count))), </span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">"forestgreen"</span>, </span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(predictive_df<span class="sc">$</span>thefts), </span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Posterior Predictive Distribution of Daily Thefts"</span>,</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Red dashed line represents the mean predicted daily count"</span>,</span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Predicted Number of Thefts"</span>,</span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability"</span>) <span class="sc">+</span></span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The constructed posterior predictive distribution seems to be centered at a mode and have slight right skew seen by how the mean is to the right of the mode.</p>
<p><strong>45 vehicles will be stolen in Chicago tomorrow</strong></p>
<p>If we wanted to predict the single best number for the number of cars stolen tomorrow the mode of the distribution would be the best estimate.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">count</span>(predictive_df, thefts) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">p =</span> n<span class="sc">/</span>n_sims)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>counts[<span class="fu">which.max</span>(counts<span class="sc">$</span>n),]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   thefts     n        p
28     45 29378 0.058756</code></pre>
</div>
</div>
<p>The most likely value is 45 with a probability of 0.058756.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(predictive_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     thefts     
 Min.   :17.00  
 1st Qu.:41.00  
 Median :45.00  
 Mean   :45.57  
 3rd Qu.:50.00  
 Max.   :82.00  </code></pre>
</div>
</div>
<p>On average we should see the rate of 45.57 cars stolen per night and a 50% chance of having less than or equal to 45 cars stolen.</p>
</section>
<section id="which-chicago-community-areas-have-the-highest-probability-of-at-least-one-motor-vehicle-theft-tomorrow" class="level2">
<h2 class="anchored" data-anchor-id="which-chicago-community-areas-have-the-highest-probability-of-at-least-one-motor-vehicle-theft-tomorrow">3. Which Chicago community areas have the highest probability of at least one motor vehicle theft tomorrow?</h2>
<p>The dataset consists of reported motor vehicle theft incidents in Chicago during 2026, obtained from the Chicago crime data portal. Each row corresponds to a single reported theft. For the purposes of this analysis, the data were aggregated to obtain the number of theft incidents per community area per day. This allows us to model theft counts as daily events occurring within each neighborhood.</p>
<p><strong>Model Specification</strong></p>
<p>Let <span class="math inline">\(Y_{jt}\)</span> denote the number of motor vehicle theft incidents in community area <span class="math inline">\(j\)</span> on day <span class="math inline">\(t\)</span>.</p>
<p>We model the number of thefts using a Poisson distribution:</p>
<p><span class="math display">\[
Y_{jt} \sim \text{Poisson}(\lambda_j)
\]</span></p>
<p>where <span class="math inline">\(\lambda_j\)</span> represents the average daily motor vehicle theft rate in community area <span class="math inline">\(j\)</span>.</p>
<p>To complete the Bayesian model, we specify a prior distribution for the unknown daily motor vehicle theft rate in each community area.</p>
<p>Let <span class="math inline">\(\lambda_j\)</span> represent the average number of motor vehicle theft incidents per day in community area <span class="math inline">\(j\)</span>. Because theft counts are modeled using a Poisson likelihood, we use a Gamma prior for <span class="math inline">\(\lambda_j\)</span>:</p>
<p><span class="math display">\[
\lambda_j \sim \text{Gamma}(\alpha, \beta)
\]</span></p>
<p>The Gamma distribution is chosen because it is conjugate to the Poisson likelihood. This conjugacy allows the posterior distribution to be obtained analytically and simplifies computation.</p>
<p><strong>Prior Evidence</strong></p>
<p>Historical motor vehicle theft data from the Chicago offense dashboard indicate that in <strong>June 2025 there were 1,473 reported motor vehicle theft incidents</strong>, which corresponds to approximately <strong>49 incidents per day citywide</strong>. Since Chicago contains <strong>77 community areas</strong>, a rough baseline rate for a typical community area is:</p>
<p><span class="math display">\[
\frac{49}{77} \approx 0.64
\]</span></p>
<p>motor vehicle theft incidents per day.</p>
<p>To incorporate this information while maintaining substantial uncertainty, we use the prior</p>
<p><span class="math display">\[
\lambda_j \sim \text{Gamma}(2,\frac{2}{0.64})
\]</span></p>
<p>This prior has mean</p>
<p><span class="math display">\[
E(\lambda_j) = \frac{\alpha}{\beta} = 0.64
\]</span></p>
<p>which reflects the approximate historical daily theft rate for a typical neighborhood while still allowing the observed 2026 data to strongly influence the posterior distribution.</p>
<p><strong>Posterior Distribution</strong></p>
<p>Let <span class="math inline">\(Y_{jt}\)</span> denote the number of motor vehicle theft incidents observed in community area <span class="math inline">\(j\)</span> on day <span class="math inline">\(t\)</span>. We assume that theft counts follow a Poisson distribution:</p>
<p><span class="math display">\[
Y_{jt} \sim \text{Poisson}(\lambda_j)
\]</span></p>
<p>where <span class="math inline">\(\lambda_j\)</span> represents the average daily motor vehicle theft rate in community area <span class="math inline">\(j\)</span>.</p>
<p>Suppose that across <span class="math inline">\(T\)</span> observed days in 2026 we observe a total of <span class="math inline">\(y_j\)</span> theft incidents in community area <span class="math inline">\(j\)</span>.</p>
<p>Given the Poisson likelihood and the Gamma prior</p>
<p><span class="math display">\[
\lambda_j \sim \text{Gamma}(\alpha,\beta)
\]</span></p>
<p>the posterior distribution is also a Gamma distribution:</p>
<p><span class="math display">\[
\lambda_j \mid data \sim \text{Gamma}(\alpha + y_j,\ \beta + T)
\]</span></p>
<p>This posterior distribution represents our updated belief about the daily motor vehicle theft rate in community area <span class="math inline">\(j\)</span> after incorporating the observed 2026 theft data.</p>
<p>The posterior mean of the theft rate is therefore</p>
<p><span class="math display">\[
E(\lambda_j \mid data) = \frac{\alpha + y_j}{\beta + T}
\]</span></p>
<p>which balances the historical prior information with the observed theft counts. Community areas with larger observed theft counts will have higher posterior rate estimates, while areas with fewer observations will be partially stabilized by the prior distribution.</p>
<p><strong>Data Summary</strong></p>
<p>The dataset contains reported motor vehicle theft incidents in Chicago from <strong>January 1, 2026 to February 22, 2026</strong>, covering a total of <strong>53 days</strong> of observations.</p>
<p>For each community area, we aggregate the data to obtain the number of theft incidents occurring on each day. This produces daily theft counts that can be modeled as event counts over time.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>crime <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/chicago_vehicle_theft_crimes_2026.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2369 Columns: 22
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (12): Case Number, Date, Block, IUCR, Primary Type, Description, Locatio...
dbl  (8): ID, Ward, Community Area, X Coordinate, Y Coordinate, Year, Latitu...
lgl  (2): Arrest, Domestic

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(crime)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,369
Columns: 22
$ ID                     &lt;dbl&gt; 14118381, 14118195, 14118379, 14117942, 1411827…
$ `Case Number`          &lt;chr&gt; "JK158640", "JK158333", "JK158602", "JK158026",…
$ Date                   &lt;chr&gt; "02/22/2026 12:00:00 AM", "02/22/2026 12:00:00 …
$ Block                  &lt;chr&gt; "063XX S MOZART ST", "051XX N CALIFORNIA AVE", …
$ IUCR                   &lt;chr&gt; "0920", "0910", "0910", "0910", "0910", "0910",…
$ `Primary Type`         &lt;chr&gt; "MOTOR VEHICLE THEFT", "MOTOR VEHICLE THEFT", "…
$ Description            &lt;chr&gt; "ATTEMPT - AUTOMOBILE", "AUTOMOBILE", "AUTOMOBI…
$ `Location Description` &lt;chr&gt; "STREET", "STREET", "STREET", "STREET", "STREET…
$ Arrest                 &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
$ Domestic               &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
$ Beat                   &lt;chr&gt; "0823", "2031", "1831", "1624", "2524", "2532",…
$ District               &lt;chr&gt; "008", "020", "018", "016", "025", "025", "008"…
$ Ward                   &lt;dbl&gt; 15, 40, 42, 38, 35, 37, 14, 50, 2, 40, 8, 24, 1…
$ `Community Area`       &lt;dbl&gt; 66, 4, 8, 15, 22, 25, 63, 2, 8, 4, 43, 29, 51, …
$ `FBI Code`             &lt;chr&gt; "07", "07", "07", "07", "07", "07", "07", "07",…
$ `X Coordinate`         &lt;dbl&gt; 1158470, 1156765, 1174220, 1140568, 1150308, 11…
$ `Y Coordinate`         &lt;dbl&gt; 1862494, 1934163, 1904299, 1927753, 1915908, 19…
$ Year                   &lt;dbl&gt; 2026, 2026, 2026, 2026, 2026, 2026, 2026, 2026,…
$ `Updated On`           &lt;chr&gt; "03/01/2026 04:09:12 PM", "03/01/2026 04:09:12 …
$ Latitude               &lt;dbl&gt; 41.77842, 41.97512, 41.89280, 41.95785, 41.9251…
$ Longitude              &lt;dbl&gt; -87.69459, -87.69890, -87.63560, -87.75862, -87…
$ Location               &lt;chr&gt; "(41.778420097, -87.69459002)", "(41.975121537,…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># clean date column for a daily date variable </span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>crime <span class="ot">&lt;-</span> crime <span class="sc">%&gt;%</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_time =</span> <span class="fu">mdy_hms</span>(Date),</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">day =</span> <span class="fu">as_date</span>(date_time),</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">community_area =</span> <span class="st">`</span><span class="at">Community Area</span><span class="st">`</span></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>crime <span class="sc">%&gt;%</span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Date, date_time, day, community_area) <span class="sc">%&gt;%</span></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  Date                   date_time           day        community_area
  &lt;chr&gt;                  &lt;dttm&gt;              &lt;date&gt;              &lt;dbl&gt;
1 02/22/2026 12:00:00 AM 2026-02-22 00:00:00 2026-02-22             66
2 02/22/2026 12:00:00 AM 2026-02-22 00:00:00 2026-02-22              4
3 02/21/2026 11:30:00 PM 2026-02-21 23:30:00 2026-02-21              8
4 02/21/2026 10:00:00 PM 2026-02-21 22:00:00 2026-02-21             15
5 02/21/2026 09:00:00 PM 2026-02-21 21:00:00 2026-02-21             22
6 02/21/2026 09:00:00 PM 2026-02-21 21:00:00 2026-02-21             25</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute number of thefts per day in each area</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>daily_counts <span class="ot">&lt;-</span> crime <span class="sc">%&gt;%</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(community_area)) <span class="sc">%&gt;%</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(community_area, day) <span class="sc">%&gt;%</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">thefts =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>daily_counts <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   community_area day        thefts
            &lt;dbl&gt; &lt;date&gt;      &lt;int&gt;
 1              1 2026-01-04      2
 2              1 2026-01-05      1
 3              1 2026-01-11      1
 4              1 2026-01-12      1
 5              1 2026-01-13      1
 6              1 2026-01-15      1
 7              1 2026-01-16      1
 8              1 2026-01-19      1
 9              1 2026-01-20      1
10              1 2026-01-21      1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># If a neighborhood had no theft on a certain day, that day still counts. Otherwise our daily rate will be too high.</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="co"># So we build a full grid of all community areas × all days.</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>all_days <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(crime<span class="sc">$</span>day, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">max</span>(crime<span class="sc">$</span>day, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">by =</span> <span class="st">"day"</span>)</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>all_areas <span class="ot">&lt;-</span> crime <span class="sc">%&gt;%</span></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(community_area)) <span class="sc">%&gt;%</span></span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(community_area)</span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>daily_complete <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">community_area =</span> all_areas<span class="sc">$</span>community_area,</span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">day =</span> all_days</span>
<span id="cb78-14"><a href="#cb78-14" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb78-15"><a href="#cb78-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(daily_counts, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"community_area"</span>, <span class="st">"day"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb78-16"><a href="#cb78-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">thefts =</span> <span class="fu">replace_na</span>(thefts, <span class="dv">0</span>))</span>
<span id="cb78-17"><a href="#cb78-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-18"><a href="#cb78-18" aria-hidden="true" tabindex="-1"></a>daily_complete <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   community_area day        thefts
            &lt;dbl&gt; &lt;date&gt;      &lt;int&gt;
 1             66 2026-01-01      1
 2             66 2026-01-02      1
 3             66 2026-01-03      4
 4             66 2026-01-04      1
 5             66 2026-01-05      1
 6             66 2026-01-06      2
 7             66 2026-01-07      1
 8             66 2026-01-08      0
 9             66 2026-01-09      0
10             66 2026-01-10      0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute total thefts and observed days for each area</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>area_summary <span class="ot">&lt;-</span> daily_complete <span class="sc">%&gt;%</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(community_area) <span class="sc">%&gt;%</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_thefts =</span> <span class="fu">sum</span>(thefts),</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">days_observed =</span> <span class="fu">n</span>(),</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_daily_mean =</span> <span class="fu">mean</span>(thefts),</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_thefts))</span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a>area_summary <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   community_area total_thefts days_observed sample_daily_mean
            &lt;dbl&gt;        &lt;int&gt;         &lt;int&gt;             &lt;dbl&gt;
 1             28          131            53              2.47
 2             24          121            53              2.28
 3             25          113            53              2.13
 4             43           78            53              1.47
 5             35           72            53              1.36
 6             71           71            53              1.34
 7             23           70            53              1.32
 8             32           68            53              1.28
 9             44           58            53              1.09
10              8           56            53              1.06</code></pre>
</div>
</div>
<p><strong>Prior</strong></p>
<p>From our source:</p>
<ul>
<li>June 2025 had <strong>1,473 incidents</strong></li>
<li>about <strong>49 incidents per day citywide</strong></li>
</ul>
<p>If we spread that across community areas as a rough baseline:</p>
<p>[ 49 / 77 ]</p>
<p>So a reasonable weak prior for a typical community area’s daily theft rate is:</p>
<p>[ _j Gamma(2, 2/0.64) ]</p>
<p>This prior has mean:</p>
<p>[ = 0.64 ]</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot gamma prior</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_gamma</span>(<span class="at">shape =</span> <span class="dv">2</span>, <span class="at">rate =</span> <span class="dv">2</span><span class="sc">/</span><span class="fl">0.64</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/plot-prior-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 1. Plot for gamma prior</p>
<p><strong>Posterior Model</strong></p>
<p>[ Y_{jt} (_j) ]</p>
<p>with prior:</p>
<p>[ _j (,) ]</p>
<p>Then posterior:</p>
<p>[ _j (+ y_j,&nbsp;+ T) ]</p>
<p>where:</p>
<ul>
<li>(y_j) = total thefts in area (j)</li>
<li>(T) = number of observed days</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Based on prior and data, compute posterior daily theft rate for each community area</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">/</span><span class="fl">0.64</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>posterior_summary <span class="ot">&lt;-</span> area_summary <span class="sc">%&gt;%</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">post_alpha =</span> alpha <span class="sc">+</span> total_thefts,</span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">post_beta =</span> beta <span class="sc">+</span> days_observed,</span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">posterior_mean =</span> post_alpha <span class="sc">/</span> post_beta,</span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_80_lower =</span> <span class="fu">qgamma</span>(<span class="fl">0.10</span>, <span class="at">shape =</span> post_alpha, <span class="at">rate =</span> post_beta),</span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_80_upper =</span> <span class="fu">qgamma</span>(<span class="fl">0.90</span>, <span class="at">shape =</span> post_alpha, <span class="at">rate =</span> post_beta),</span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_95_lower =</span> <span class="fu">qgamma</span>(<span class="fl">0.025</span>, <span class="at">shape =</span> post_alpha, <span class="at">rate =</span> post_beta),</span>
<span id="cb83-12"><a href="#cb83-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_95_upper =</span> <span class="fu">qgamma</span>(<span class="fl">0.975</span>, <span class="at">shape =</span> post_alpha, <span class="at">rate =</span> post_beta)</span>
<span id="cb83-13"><a href="#cb83-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb83-14"><a href="#cb83-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(posterior_mean))</span>
<span id="cb83-15"><a href="#cb83-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-16"><a href="#cb83-16" aria-hidden="true" tabindex="-1"></a>posterior_summary <span class="sc">%&gt;%</span></span>
<span id="cb83-17"><a href="#cb83-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(community_area, total_thefts, days_observed, posterior_mean,</span>
<span id="cb83-18"><a href="#cb83-18" aria-hidden="true" tabindex="-1"></a>         ci_80_lower, ci_80_upper) <span class="sc">%&gt;%</span></span>
<span id="cb83-19"><a href="#cb83-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   community_area total_thefts days_observed posterior_mean ci_80_lower
            &lt;dbl&gt;        &lt;int&gt;         &lt;int&gt;          &lt;dbl&gt;       &lt;dbl&gt;
 1             28          131            53           2.37       2.11 
 2             24          121            53           2.19       1.94 
 3             25          113            53           2.05       1.81 
 4             43           78            53           1.43       1.23 
 5             35           72            53           1.32       1.13 
 6             71           71            53           1.30       1.11 
 7             23           70            53           1.28       1.09 
 8             32           68            53           1.25       1.06 
 9             44           58            53           1.07       0.896
10              8           56            53           1.03       0.864
# ℹ 1 more variable: ci_80_upper &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The posterior estimates show substantial variation in daily motor vehicle theft rates across Chicago communnity areas. Using the Gamma–Poisson model with a prior informed by historical Chicago theft trends, we estimated the posterior daily theft rate for each community area based on the 53 days of observed data in 2026.For example, community area 28 had the highest posterior mean daily theft rate. Across the 53 observed days, this area experienced 131 theft incidents, corresponding to an estimated posterior mean of 2.37 thefts per day. Additionally, given the model and the data, there is an 80% probability that the true average daily theft rate in this area lies between approximately 2.11 and 2.64 thefts per day.</p>
<p>An example posterior plot:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prior</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">/</span> <span class="fl">0.64</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Data for Area 28</span></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>T_days <span class="ot">&lt;-</span> <span class="dv">53</span></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>y_28 <span class="ot">&lt;-</span> <span class="dv">131</span></span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_gamma_poisson</span>(</span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">shape =</span> alpha,</span>
<span id="cb85-11"><a href="#cb85-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">rate =</span> beta,</span>
<span id="cb85-12"><a href="#cb85-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> T_days,</span>
<span id="cb85-13"><a href="#cb85-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">sum_y =</span> y_28</span>
<span id="cb85-14"><a href="#cb85-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/plot-posterior-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 2. Posterior distribution for community area 28</p>
<p>For area 28, the posterior distribution is shifted noticeably to the right of the prior, indicating that the observed 2026 data suggest a higher daily theft rate than the baseline prior expectation. The posterior is also narrower than the prior, showing that the 53 days of observed data reduce uncertainty about the true rate.</p>
<p>These posterior rate estimates are then used to generate posterior predictive simulations for tomorrow’s theft counts. From these simulations, we compute the probability that at least one theft occurs in each community area tomorrow, allowing us to identify neighborhoods with the highest short-term risk of motor vehicle theft.</p>
<p><strong>Predictive Simulation</strong></p>
<p>While the posterior distribution describes the uncertainty in the underlying theft rate <span class="math inline">\(\lambda_j\)</span>, our primary goal is to predict future theft incidents.</p>
<p>Let</p>
<p><span class="math display">\[
Y_{j,\text{tomorrow}}
\]</span></p>
<p>denote the number of motor vehicle theft incidents that occur tomorrow in community area <span class="math inline">\(j\)</span>.</p>
<p>The posterior predictive distribution is defined as</p>
<p><span class="math display">\[
P(Y_{j,\text{tomorrow}} \mid data)
\]</span></p>
<p>which integrates over the uncertainty in the theft rate parameter <span class="math inline">\(\lambda_j\)</span>.</p>
<p>To approximate this distribution, we use simulation:</p>
<ol type="1">
<li>Draw <span class="math inline">\(\lambda_j\)</span> from the posterior distribution</li>
<li>Simulate a theft count from a Poisson distribution with rate <span class="math inline">\(\lambda_j\)</span></li>
<li>Repeat this process many times</li>
</ol>
<p>This produces simulated values of <span class="math inline">\(Y_{j,\text{tomorrow}}\)</span> that approximate the posterior predictive distribution.</p>
<p>A useful risk measure derived from this distribution is</p>
<p><span class="math display">\[
P(Y_{j,\text{tomorrow}} \ge 1 \mid data)
\]</span></p>
<p>which represents the probability that at least one motor vehicle theft occurs tomorrow in community area <span class="math inline">\(j\)</span>. Community areas with the highest values of this probability are identified as the neighborhoods with the highest predicted short-term theft risk.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">84735</span>)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>n_sims <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> posterior_summary <span class="sc">%&gt;%</span></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sim_lambda =</span> <span class="fu">list</span>(<span class="fu">rgamma</span>(n_sims, <span class="at">shape =</span> post_alpha, <span class="at">rate =</span> post_beta)),</span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">sim_tomorrow =</span> <span class="fu">list</span>(<span class="fu">rpois</span>(n_sims, <span class="at">lambda =</span> sim_lambda)),</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_mean =</span> <span class="fu">mean</span>(sim_tomorrow),</span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_median =</span> <span class="fu">median</span>(sim_tomorrow),</span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob_at_least_1 =</span> <span class="fu">mean</span>(sim_tomorrow <span class="sc">&gt;=</span> <span class="dv">1</span>),</span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob_at_least_2 =</span> <span class="fu">mean</span>(sim_tomorrow <span class="sc">&gt;=</span> <span class="dv">2</span>),</span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_80_lower =</span> <span class="fu">quantile</span>(sim_tomorrow, <span class="fl">0.10</span>),</span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_80_upper =</span> <span class="fu">quantile</span>(sim_tomorrow, <span class="fl">0.90</span>)</span>
<span id="cb86-16"><a href="#cb86-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb86-17"><a href="#cb86-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rank area </span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>top_risk <span class="ot">&lt;-</span> predictions <span class="sc">%&gt;%</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(prob_at_least_1)) <span class="sc">%&gt;%</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>    community_area,</span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>    posterior_mean,</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>    pred_mean,</span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>    prob_at_least_1,</span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>    prob_at_least_2,</span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>    pred_80_lower,</span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a>    pred_80_upper</span>
<span id="cb87-12"><a href="#cb87-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb87-13"><a href="#cb87-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>)</span>
<span id="cb87-14"><a href="#cb87-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-15"><a href="#cb87-15" aria-hidden="true" tabindex="-1"></a>top_risk</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 7
   community_area posterior_mean pred_mean prob_at_least_1 prob_at_least_2
            &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;
 1             28           2.37      2.38           0.908           0.682
 2             24           2.19      2.19           0.888           0.645
 3             25           2.05      2.05           0.868           0.602
 4             43           1.43      1.42           0.756           0.416
 5             35           1.32      1.33           0.739           0.380
 6             71           1.30      1.30           0.726           0.370
 7             23           1.28      1.27           0.719           0.360
 8             32           1.25      1.25           0.713           0.357
 9             44           1.07      1.06           0.655           0.291
10              8           1.03      1.02           0.636           0.268
# ℹ 2 more variables: pred_80_lower &lt;dbl&gt;, pred_80_upper &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Columns specification and Area Decode</strong></p>
<ul>
<li><p>posterior_mean = estimated average thefts per day in that area</p></li>
<li><p>pred_mean = predicted number of thefts tomoorrow</p></li>
<li><p>prob_at least_1 = probability of at least 1 theft tomorrow</p></li>
<li><p>prob_at least_2 = probability of at least 2 or more theft tomorrow</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># join area using code from the data to make further interpretation </span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>area_lookup <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>community_area, <span class="sc">~</span>neighborhood,</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="dv">8</span>, <span class="st">"Near North Side"</span>,</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">23</span>, <span class="st">"Humboldt Park"</span>,</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="dv">24</span>, <span class="st">"West Town"</span>,</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>  <span class="dv">25</span>, <span class="st">"Austin"</span>,</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>  <span class="dv">28</span>, <span class="st">"Near West Side"</span>,</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>  <span class="dv">32</span>, <span class="st">"Loop"</span>,</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>  <span class="dv">35</span>, <span class="st">"Douglas"</span>,</span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>  <span class="dv">43</span>, <span class="st">"South Shore"</span>,</span>
<span id="cb89-12"><a href="#cb89-12" aria-hidden="true" tabindex="-1"></a>  <span class="dv">44</span>, <span class="st">"Chatham"</span>,</span>
<span id="cb89-13"><a href="#cb89-13" aria-hidden="true" tabindex="-1"></a>  <span class="dv">71</span>, <span class="st">"Auburn Gresham"</span></span>
<span id="cb89-14"><a href="#cb89-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb89-15"><a href="#cb89-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-16"><a href="#cb89-16" aria-hidden="true" tabindex="-1"></a>results_named <span class="ot">&lt;-</span> top_risk <span class="sc">%&gt;%</span></span>
<span id="cb89-17"><a href="#cb89-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(area_lookup, <span class="at">by =</span> <span class="st">"community_area"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb89-18"><a href="#cb89-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb89-19"><a href="#cb89-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">area_label =</span> <span class="fu">paste0</span>(neighborhood, <span class="st">" ("</span>, community_area, <span class="st">")"</span>)</span>
<span id="cb89-20"><a href="#cb89-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># visualize results</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  results_named <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(prob_at_least_1),</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(area_label, prob_at_least_1), <span class="at">y =</span> prob_at_least_1)</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">percent_format</span>(<span class="at">accuracy =</span> <span class="dv">1</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Predicted probability of at least one motor vehicle theft tomorrow"</span>,</span>
<span id="cb90-11"><a href="#cb90-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Top 10 Chicago community areas from posterior predictive simulation"</span>,</span>
<span id="cb90-12"><a href="#cb90-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Community area"</span>,</span>
<span id="cb90-13"><a href="#cb90-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Probability"</span></span>
<span id="cb90-14"><a href="#cb90-14" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/plot-pred-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 3. Visualization of posterior predictive probability of at least one motor vehicle theft occurring tomorrow for top 10 high-risk areas in Chicago.</p>
<p><strong>Results</strong></p>
<p>Using the Bayesian Gamma–Poisson model, we estimated the daily motor vehicle theft rate for each Chicago community area and generated posterior predictive simulations to estimate the probability of future theft incidents. These predictions allow us to identify neighborhoods with the highest short-term theft risk.</p>
<p>The results indicate that <strong>Near West Side (Community Area 28)</strong> has the highest predicted risk of motor vehicle theft. Over the 53 observed days, this area experienced <strong>131 theft incidents</strong>, producing a posterior mean estimate of <strong>2.37 thefts per day</strong>. Posterior predictive simulations suggest an expected value of approximately <strong>2.38 thefts tomorrow</strong>, with a <strong>90.8% probability of at least one theft occurring tomorrow</strong> and a <strong>68.2% probability of two or more thefts</strong>.</p>
<p>The next highest risk area is <strong>West Town (Community Area 24)</strong>, which recorded <strong>121 theft incidents</strong> during the observation period. The posterior mean daily theft rate is <strong>2.19 thefts per day</strong>, and the predicted probability of at least one theft tomorrow is approximately <strong>88.8%</strong>, with a <strong>64.5% probability of at least two thefts</strong>.</p>
<p>Similarly, <strong>Austin (Community Area 25)</strong> shows elevated theft risk. With <strong>113 observed incidents</strong>, the posterior mean theft rate is estimated at <strong>2.05 thefts per day</strong>, corresponding to an <strong>86.8% probability of at least one theft tomorrow</strong>.</p>
<p>Several other neighborhoods also demonstrate substantial predicted theft risk. For example, <strong>South Shore (Community Area 43)</strong> has a posterior mean rate of <strong>1.43 thefts per day</strong> and a <strong>75.6% probability of at least one theft tomorrow</strong>. <strong>Douglas (Community Area 35)</strong> and <strong>Auburn Gresham (Community Area 71)</strong> have posterior mean daily theft rates of approximately <strong>1.32 and 1.30 thefts per day</strong>, with predicted probabilities of at least one theft tomorrow of <strong>73.9% and 72.6%</strong>, respectively.</p>
<p>Other areas in the top-risk group include <strong>Humboldt Park (Community Area 23)</strong> and <strong>Loop (Community Area 32)</strong>, both of which show posterior mean daily theft rates slightly above <strong>1.24 thefts per day</strong>, corresponding to predicted probabilities of at least one theft tomorrow of approximately <strong>71–72%</strong>.</p>
<p>Even neighborhoods with comparatively lower estimated rates still exhibit notable theft risk. For example, <strong>Chatham (Community Area 44)</strong> and <strong>Near North Side (Community Area 8)</strong> have posterior mean daily theft rates of approximately <strong>1.07 and 1.03 thefts per day</strong>, respectively. These rates correspond to predicted probabilities of at least one theft tomorrow of <strong>65.5% and 63.7%</strong>.</p>
<p>Overall, the posterior predictive results suggest that several Chicago neighborhoods consistently experience higher daily motor vehicle theft rates.</p>
<p><strong>Model Evaluation</strong></p>
<p>To assess model performance, we conducted posterior predictive checks by generating replicated datasets from the fitted Gamma–Poisson model. For each community area, we simulated theft counts across the 53-day observation period using posterior draws of the daily theft rate.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate replicated dataset </span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">84735</span>)</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>n_rep <span class="ot">&lt;-</span> <span class="dv">5000</span></span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>ppc_data <span class="ot">&lt;-</span> posterior_summary <span class="sc">%&gt;%</span></span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb91-8"><a href="#cb91-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb91-9"><a href="#cb91-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">lambda_draw =</span> <span class="fu">list</span>(<span class="fu">rgamma</span>(n_rep, post_alpha, post_beta)),</span>
<span id="cb91-10"><a href="#cb91-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y_rep =</span> <span class="fu">list</span>(<span class="fu">rpois</span>(n_rep, lambda_draw <span class="sc">*</span> days_observed))</span>
<span id="cb91-11"><a href="#cb91-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb91-12"><a href="#cb91-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute average simulated count</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>ppc_summary <span class="ot">&lt;-</span> ppc_data <span class="sc">%&gt;%</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sim_mean =</span> <span class="fu">map_dbl</span>(y_rep, mean),</span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sim_sd =</span> <span class="fu">map_dbl</span>(y_rep, sd)</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>ppc_summary <span class="sc">%&gt;%</span></span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(community_area, total_thefts, sim_mean, sim_sd) <span class="sc">%&gt;%</span></span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   community_area total_thefts sim_mean sim_sd
            &lt;dbl&gt;        &lt;int&gt;    &lt;dbl&gt;  &lt;dbl&gt;
 1             28          131    126.    15.6
 2             24          121    116.    15.1
 3             25          113    109.    14.5
 4             43           78     75.5   12.2
 5             35           72     70.0   11.8
 6             71           71     68.9   11.6
 7             23           70     67.9   11.4
 8             32           68     66.0   11.5
 9             44           58     56.8   10.6
10              8           56     54.7   10.2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># visualize ppc</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ppc_summary,</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> sim_mean, <span class="at">y =</span> total_thefts)) <span class="sc">+</span></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Posterior Predictive Check"</span>,</span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Observed vs simulated theft counts"</span>,</span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Simulated mean theft counts"</span>,</span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Observed theft counts"</span></span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb94-12"><a href="#cb94-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/eval-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 4. Relationship between the simulated mean theft counts and the observed theft counts across community areas.</p>
<p>Most points lie close to this diagonal which indicates that the simulated data generated by the model closely match the observed counts. This suggests that the Gamma–Poisson model captures the overall pattern of motor vehicle theft incidents across Chicago neighborhoods.</p>
<p>Some neighborhoods with very high theft counts show slightly higher observed values than predicted, suggesting that the model may slightly underestimate extreme theft counts. This may reflect mild overdispersion in the data relative to the Poisson assumption. However, the deviations are small, and overall the posterior predictive check indicates that the model provides a reasonable fit to the observed data.</p>
<p><strong>Discussion and Limitations</strong></p>
<p>While the Bayesian Gamma–Poisson model provides a useful framework for estimating and predicting motor vehicle theft risk, several limitations should be considered when interpreting the results.</p>
<ol type="1">
<li><p>The dataset used in this analysis covers only 53 days of observations (January 1 to February 22, 2026). Because crime patterns may vary seasonally, the observed theft rates during this short time window may not fully represent long-term patterns throughout the year. For example, vehicle theft rates may change during summer months or holiday periods when vehicle usage patterns differ.</p></li>
<li><p>The model assumes that theft incidents within each community area follow a Poisson process with a constant daily rate. This assumption implies that events occur independently and that the average theft rate does not change over the observed period. In reality, theft incidents may be influenced by factors such as police activity, local events, economic conditions, or organized crime patterns, which may introduce temporal variation that the model does not explicitly capture.</p></li>
<li><p>The analysis relies on reported motor vehicle theft incidents from the Chicago crime dataset. Not all theft incidents may be reported to law enforcement, and reporting rates may vary across neighborhoods. As a result, the observed counts may underestimate the true number of theft incidents.</p></li>
<li><p>The prior distribution used in the model is based on historical citywide theft statistics, rather than neighborhood-specific historical data. While this provides a reasonable baseline estimate for the typical daily theft rate, it may not fully reflect local variations between community areas.</p></li>
</ol>
<p>Despite these limitations, the framework have several advantages. Combining prior and observed data stabilizes estimates in neighborhoods with limited observations and allows uncertainty in the theft rates to be formally quantified. The posterior predictive simulations also provide interpretable risk measures, such as the probability that at least one theft occurs tomorrow, which can be used to compare short-term theft risk across neighborhoods.</p>
<p>Future work could extend this analysis by incorporating longer time periods, seasonal effects, or additional predictors such as socioeconomic variables, traffic patterns, or law enforcement activity. More advanced hierarchical or spatial Bayesian models could also be used to capture correlations between neighboring areas and improve risk prediction.</p>
</section>
<section id="does-the-probability-of-arrest-for-motor-vehicle-theft-vary-by-community-area-in-chicago-in-2026" class="level2">
<h2 class="anchored" data-anchor-id="does-the-probability-of-arrest-for-motor-vehicle-theft-vary-by-community-area-in-chicago-in-2026">4. Does the probability of arrest for motor vehicle theft vary by community area in Chicago in 2026?</h2>
<p>Here, we investigate whether the probability of arrest for vehicle theft differs by community area in Chicago.</p>
<p>We start with defining a Bayes model. A natural choice is a Beta Binomial model. We define:</p>
<p><span class="math inline">\(y_j\)</span> = number of motor-vehicle-theft incidents that resulted in an arrest in area <span class="math inline">\(j\)</span>.</p>
<p><span class="math inline">\(n_j\)</span> = total number of motor-vehicle-theft incidents in area <span class="math inline">\(j\)</span>.</p>
<p><span class="math inline">\(\pi_j = P(\text{arrest} \mid \text{MVT in area } j)\)</span>.</p>
<p><span class="math display">\[\pi_j \sim \text{Beta}(\alpha, \beta)\]</span> Likelihood: <span class="math display">\[y_j \mid \pi_j \sim \text{Binomial}(n_j, \pi_j)\]</span> Posterior: <span class="math display">\[\pi_j \mid \text{data} \sim \text{Beta}(\alpha + y_j, \ \beta + n_j - y_j)\]</span></p>
<p>Nationally, only about 10% of vehicle thefts result in an arrest. We can start with this assumption and set our prior to about <span class="math inline">\(\pi_j \sim \text{Beta}(2, 18)\)</span>, which has a mean of 0.1.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_beta</span>(<span class="dv">2</span>,<span class="dv">18</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now, we load our data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/chicago_vehicle_theft_crimes_2026.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">arrest_numeric =</span> <span class="fu">ifelse</span>(Arrest <span class="sc">==</span> <span class="st">"true"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ID Case.Number                   Date                  Block IUCR
1 14118381    JK158640 02/22/2026 12:00:00 AM      063XX S MOZART ST  920
2 14118195    JK158333 02/22/2026 12:00:00 AM 051XX N CALIFORNIA AVE  910
3 14118379    JK158602 02/21/2026 11:30:00 PM    006XX N FRANKLIN ST  910
4 14117942    JK158026 02/21/2026 10:00:00 PM  052XX W HUTCHINSON ST  910
5 14118271    JK158463 02/21/2026 09:00:00 PM      024XX N AVERS AVE  910
6 14118560    JK158906 02/21/2026 09:00:00 PM       018XX N LONG AVE  910
         Primary.Type          Description Location.Description Arrest Domestic
1 MOTOR VEHICLE THEFT ATTEMPT - AUTOMOBILE               STREET  false    false
2 MOTOR VEHICLE THEFT           AUTOMOBILE               STREET  false    false
3 MOTOR VEHICLE THEFT           AUTOMOBILE               STREET  false    false
4 MOTOR VEHICLE THEFT           AUTOMOBILE               STREET  false    false
5 MOTOR VEHICLE THEFT           AUTOMOBILE               STREET  false    false
6 MOTOR VEHICLE THEFT           AUTOMOBILE               STREET  false    false
  Beat District Ward Community.Area FBI.Code X.Coordinate Y.Coordinate Year
1  823        8   15             66        7      1158470      1862494 2026
2 2031       20   40              4        7      1156765      1934163 2026
3 1831       18   42              8        7      1174220      1904299 2026
4 1624       16   38             15        7      1140568      1927753 2026
5 2524       25   35             22        7      1150308      1915908 2026
6 2532       25   37             25        7      1140108      1911620 2026
              Updated.On Latitude Longitude                      Location
1 03/01/2026 04:09:12 PM 41.77842 -87.69459  (41.778420097, -87.69459002)
2 03/01/2026 04:09:12 PM 41.97512 -87.69890 (41.975121537, -87.698898525)
3 03/01/2026 04:09:12 PM 41.89280 -87.63560 (41.892800977, -87.635604802)
4 03/01/2026 04:09:12 PM 41.95785 -87.75862 (41.957845658, -87.758619084)
5 03/01/2026 04:09:12 PM 41.92516 -87.72312 (41.925157193, -87.723121175)
6 03/01/2026 04:09:12 PM 41.91358 -87.76071 (41.913583518, -87.760706384)
  arrest_numeric
1              0
2              0
3              0
4              0
5              0
6              0</code></pre>
</div>
</div>
<p>Compute <span class="math inline">\(\pi_j\)</span> for each area.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>district_counts <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(District) <span class="sc">%&gt;%</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),                    <span class="co"># total incidents</span></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fu">sum</span>(arrest_numeric),    <span class="co"># arrests</span></span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">observed_rate =</span> y<span class="sc">/</span>n</span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span>
<span id="cb98-9"><a href="#cb98-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-10"><a href="#cb98-10" aria-hidden="true" tabindex="-1"></a>district_counts</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 22 × 4
   District     n     y observed_rate
      &lt;int&gt; &lt;int&gt; &lt;dbl&gt;         &lt;dbl&gt;
 1       12   213     0        0     
 2        2   212     6        0.0283
 3        4   176     3        0.0170
 4        8   163     4        0.0245
 5        6   153     5        0.0327
 6       11   128    10        0.0781
 7        1   126     3        0.0238
 8       25   124     4        0.0323
 9        3   122     4        0.0328
10        9   103     3        0.0291
# ℹ 12 more rows</code></pre>
</div>
</div>
<p>Now using the Beta-Binomial closed form, lets update the posterior for each district.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>alpha_prior <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>beta_prior <span class="ot">&lt;-</span> <span class="dv">18</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>district_posteriors <span class="ot">&lt;-</span> district_counts <span class="sc">%&gt;%</span></span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha_post =</span> alpha_prior <span class="sc">+</span> y,</span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">beta_post =</span> beta_prior <span class="sc">+</span> n <span class="sc">-</span> y,</span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb100-9"><a href="#cb100-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">posterior_mean =</span> alpha_post <span class="sc">/</span> (alpha_post <span class="sc">+</span> beta_post),</span>
<span id="cb100-10"><a href="#cb100-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb100-11"><a href="#cb100-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_lower =</span> <span class="fu">qbeta</span>(<span class="fl">0.025</span>, alpha_post, beta_post),</span>
<span id="cb100-12"><a href="#cb100-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_upper =</span> <span class="fu">qbeta</span>(<span class="fl">0.975</span>, alpha_post, beta_post)</span>
<span id="cb100-13"><a href="#cb100-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb100-14"><a href="#cb100-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-15"><a href="#cb100-15" aria-hidden="true" tabindex="-1"></a>district_posteriors</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 22 × 9
   District     n     y observed_rate alpha_post beta_post posterior_mean
      &lt;int&gt; &lt;int&gt; &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;          &lt;dbl&gt;
 1       12   213     0        0               2       231        0.00858
 2        2   212     6        0.0283          8       224        0.0345 
 3        4   176     3        0.0170          5       191        0.0255 
 4        8   163     4        0.0245          6       177        0.0328 
 5        6   153     5        0.0327          7       166        0.0405 
 6       11   128    10        0.0781         12       136        0.0811 
 7        1   126     3        0.0238          5       141        0.0342 
 8       25   124     4        0.0323          6       138        0.0417 
 9        3   122     4        0.0328          6       136        0.0423 
10        9   103     3        0.0291          5       118        0.0407 
# ℹ 12 more rows
# ℹ 2 more variables: ci_lower &lt;dbl&gt;, ci_upper &lt;dbl&gt;</code></pre>
</div>
</div>
<p>As we can see from this table, between-group posterior means are quite different. Comparing between district 12 and district 11 for instance, we can see quite a large difference.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_beta_binomial</span>(<span class="dv">2</span>, <span class="dv">18</span>, <span class="at">y=</span><span class="dv">0</span>, <span class="at">n=</span><span class="dv">213</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_beta_binomial</span>(<span class="dv">2</span>,<span class="dv">18</span>,<span class="at">y=</span><span class="dv">10</span>,<span class="at">n=</span><span class="dv">128</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-45-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>district_posteriors <span class="sc">%&gt;%</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(posterior_mean) <span class="sc">%&gt;%</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">District =</span> <span class="fu">factor</span>(District, <span class="at">levels =</span> District)) <span class="sc">%&gt;%</span></span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> posterior_mean, <span class="at">y =</span> District)) <span class="sc">+</span></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> ci_lower, <span class="at">xmax =</span> ci_upper), <span class="at">height =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Posterior Arrest Probability by District"</span>,</span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Posterior Mean Arrest Probability"</span>,</span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"District"</span></span>
<span id="cb104-11"><a href="#cb104-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb104-12"><a href="#cb104-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `geom_errorbarh()` was deprecated in ggplot2 4.0.0.
ℹ Please use the `orientation` argument of `geom_errorbar()` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`height` was translated to `width`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Using a Beta(2,18) prior centered at a 10% arrest rate, we updated our beliefs about the arrest probability for motor vehicle theft in each district. We have plotted the confidence intervals for each district above,</p>
<p>Now we’d like to statistically compute whether arrest proportions differ by district in Chicago. Formally, we compute <span class="math inline">\(P(\pi_i &gt; \pi_j)\)</span> for all pairs of district i and district j. In order to do this, we sample from the posterior distribution of each district and compare the samples.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>num_samples <span class="ot">&lt;-</span> <span class="dv">5000</span></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>district_names <span class="ot">&lt;-</span> district_posteriors<span class="sc">$</span>District</span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>num_districts <span class="ot">&lt;-</span> <span class="fu">length</span>(district_names)</span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-7"><a href="#cb107-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate samples for each district</span></span>
<span id="cb107-8"><a href="#cb107-8" aria-hidden="true" tabindex="-1"></a>posterior_samples <span class="ot">&lt;-</span> <span class="fu">lapply</span>(</span>
<span id="cb107-9"><a href="#cb107-9" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span><span class="sc">:</span>num_districts,</span>
<span id="cb107-10"><a href="#cb107-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(i){</span>
<span id="cb107-11"><a href="#cb107-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rbeta</span>(</span>
<span id="cb107-12"><a href="#cb107-12" aria-hidden="true" tabindex="-1"></a>      num_samples,</span>
<span id="cb107-13"><a href="#cb107-13" aria-hidden="true" tabindex="-1"></a>      district_posteriors<span class="sc">$</span>alpha_post[i],</span>
<span id="cb107-14"><a href="#cb107-14" aria-hidden="true" tabindex="-1"></a>      district_posteriors<span class="sc">$</span>beta_post[i]</span>
<span id="cb107-15"><a href="#cb107-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb107-16"><a href="#cb107-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb107-17"><a href="#cb107-17" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Next, we compare every pair of districts and compute the probability that one has a higher arrest rate than the other.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>pairwise_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="cn">NA</span>,</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrow =</span> num_districts,</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ncol =</span> num_districts,</span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimnames =</span> <span class="fu">list</span>(district_names, district_names)</span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-8"><a href="#cb108-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num_districts){</span>
<span id="cb108-9"><a href="#cb108-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num_districts){</span>
<span id="cb108-10"><a href="#cb108-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb108-11"><a href="#cb108-11" aria-hidden="true" tabindex="-1"></a>    samples_i <span class="ot">&lt;-</span> posterior_samples[[i]]</span>
<span id="cb108-12"><a href="#cb108-12" aria-hidden="true" tabindex="-1"></a>    samples_j <span class="ot">&lt;-</span> posterior_samples[[j]]</span>
<span id="cb108-13"><a href="#cb108-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb108-14"><a href="#cb108-14" aria-hidden="true" tabindex="-1"></a>    pairwise_matrix[i, j] <span class="ot">&lt;-</span> <span class="fu">mean</span>(samples_i <span class="sc">&gt;</span> samples_j)</span>
<span id="cb108-15"><a href="#cb108-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb108-16"><a href="#cb108-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb108-17"><a href="#cb108-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb108-18"><a href="#cb108-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-19"><a href="#cb108-19" aria-hidden="true" tabindex="-1"></a>pairwise_matrix</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       12      2      4      8      6     11      1     25      3      9     14
12 0.0000 0.0192 0.0762 0.0278 0.0134 0.0000 0.0322 0.0148 0.0130 0.0182 0.0204
2  0.9808 0.0000 0.7208 0.5480 0.3906 0.0224 0.5188 0.3740 0.3544 0.4008 0.3938
4  0.9238 0.2792 0.0000 0.3268 0.2012 0.0066 0.3088 0.2072 0.1858 0.2292 0.2266
8  0.9722 0.4520 0.6732 0.0000 0.3574 0.0282 0.4708 0.3360 0.3264 0.3626 0.3658
6  0.9866 0.6094 0.7988 0.6426 0.0000 0.0552 0.6162 0.4816 0.4576 0.5138 0.5056
11 1.0000 0.9776 0.9934 0.9718 0.9448 0.0000 0.9666 0.9318 0.9200 0.9314 0.9230
1  0.9678 0.4812 0.6912 0.5292 0.3838 0.0334 0.0000 0.3728 0.3488 0.3948 0.3988
25 0.9852 0.6260 0.7928 0.6640 0.5184 0.0682 0.6272 0.0000 0.4802 0.5182 0.5134
3  0.9870 0.6456 0.8142 0.6736 0.5424 0.0800 0.6512 0.5198 0.0000 0.5454 0.5318
9  0.9818 0.5992 0.7708 0.6374 0.4862 0.0686 0.6052 0.4818 0.4546 0.0000 0.4966
14 0.9796 0.6062 0.7734 0.6342 0.4944 0.0770 0.6012 0.4866 0.4682 0.5034 0.0000
7  0.9998 0.9820 0.9926 0.9816 0.9534 0.5980 0.9712 0.9452 0.9432 0.9402 0.9386
5  0.9062 0.3572 0.5374 0.3946 0.2694 0.0270 0.3786 0.2694 0.2530 0.2944 0.2880
16 0.9904 0.7190 0.8556 0.7488 0.6254 0.1554 0.7238 0.6204 0.5906 0.6278 0.6196
19 0.9754 0.5968 0.7704 0.6430 0.5116 0.0974 0.6120 0.5014 0.4730 0.5236 0.5104
18 0.9230 0.4282 0.6100 0.4654 0.3422 0.0502 0.4446 0.3382 0.3202 0.3660 0.3532
15 0.9952 0.7938 0.8978 0.8102 0.7026 0.2174 0.7882 0.6950 0.6772 0.7088 0.6976
22 0.9962 0.8060 0.9016 0.8190 0.7300 0.2438 0.8016 0.7072 0.6932 0.7162 0.7178
24 0.9824 0.6908 0.8228 0.7056 0.6022 0.1448 0.6898 0.5808 0.5684 0.5954 0.5972
10 0.9996 0.9574 0.9830 0.9626 0.9262 0.5426 0.9530 0.9112 0.9092 0.9128 0.9136
17 0.9874 0.7392 0.8578 0.7654 0.6594 0.1860 0.7394 0.6384 0.6260 0.6496 0.6432
20 0.9182 0.5094 0.6520 0.5404 0.4316 0.1138 0.5210 0.4278 0.4146 0.4456 0.4442
        7      5     16     19     18     15     22     24     10     17     20
12 0.0002 0.0938 0.0096 0.0246 0.0770 0.0048 0.0038 0.0176 0.0004 0.0126 0.0818
2  0.0180 0.6428 0.2810 0.4032 0.5718 0.2062 0.1940 0.3092 0.0426 0.2608 0.4906
4  0.0074 0.4626 0.1444 0.2296 0.3900 0.1022 0.0984 0.1772 0.0170 0.1422 0.3480
8  0.0184 0.6054 0.2512 0.3570 0.5346 0.1898 0.1810 0.2944 0.0374 0.2346 0.4596
6  0.0466 0.7306 0.3746 0.4884 0.6578 0.2974 0.2700 0.3978 0.0738 0.3406 0.5684
11 0.4020 0.9730 0.8446 0.9026 0.9498 0.7826 0.7562 0.8552 0.4574 0.8140 0.8862
1  0.0288 0.6214 0.2762 0.3880 0.5554 0.2118 0.1984 0.3102 0.0470 0.2606 0.4790
25 0.0548 0.7306 0.3796 0.4986 0.6618 0.3050 0.2928 0.4192 0.0888 0.3616 0.5722
3  0.0568 0.7470 0.4094 0.5270 0.6798 0.3228 0.3068 0.4316 0.0908 0.3740 0.5854
9  0.0598 0.7056 0.3722 0.4764 0.6340 0.2912 0.2838 0.4046 0.0872 0.3504 0.5544
14 0.0614 0.7120 0.3804 0.4896 0.6468 0.3024 0.2822 0.4028 0.0864 0.3568 0.5558
7  0.0000 0.9812 0.8812 0.9202 0.9626 0.8258 0.8088 0.8788 0.5358 0.8430 0.9036
5  0.0188 0.0000 0.1988 0.2852 0.4372 0.1508 0.1418 0.2314 0.0364 0.1922 0.3768
16 0.1188 0.8012 0.0000 0.6026 0.7422 0.4256 0.3930 0.5268 0.1550 0.4652 0.6548
19 0.0798 0.7148 0.3974 0.0000 0.6504 0.3222 0.3040 0.4214 0.1102 0.3690 0.5630
18 0.0374 0.5628 0.2578 0.3496 0.0000 0.2070 0.1838 0.2890 0.0558 0.2432 0.4324
15 0.1742 0.8492 0.5744 0.6778 0.7930 0.0000 0.4774 0.6008 0.2168 0.5380 0.7092
22 0.1912 0.8582 0.6070 0.6960 0.8162 0.5226 0.0000 0.6096 0.2282 0.5522 0.7176
24 0.1212 0.7686 0.4732 0.5786 0.7110 0.3992 0.3904 0.0000 0.1566 0.4470 0.6238
10 0.4642 0.9636 0.8450 0.8898 0.9442 0.7832 0.7718 0.8434 0.0000 0.8068 0.8872
17 0.1570 0.8078 0.5348 0.6310 0.7568 0.4620 0.4478 0.5530 0.1932 0.0000 0.6674
20 0.0964 0.6232 0.3452 0.4370 0.5676 0.2908 0.2824 0.3762 0.1128 0.3326 0.0000</code></pre>
</div>
</div>
<p>We create a heatmap to identify the strongest differences.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>pairwise_df <span class="ot">&lt;-</span> <span class="fu">melt</span>(pairwise_matrix)</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(pairwise_df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"District_i"</span>, <span class="st">"District_j"</span>, <span class="st">"Probability"</span>)</span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pairwise_df, <span class="fu">aes</span>(<span class="at">x =</span> District_j, <span class="at">y =</span> District_i, <span class="at">fill =</span> Probability)) <span class="sc">+</span></span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb110-7"><a href="#cb110-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(</span>
<span id="cb110-8"><a href="#cb110-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">low =</span> <span class="st">"blue"</span>,</span>
<span id="cb110-9"><a href="#cb110-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">mid =</span> <span class="st">"white"</span>,</span>
<span id="cb110-10"><a href="#cb110-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">high =</span> <span class="st">"red"</span>,</span>
<span id="cb110-11"><a href="#cb110-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">midpoint =</span> <span class="fl">0.5</span>,</span>
<span id="cb110-12"><a href="#cb110-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb110-13"><a href="#cb110-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb110-14"><a href="#cb110-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb110-15"><a href="#cb110-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Pairwise Posterior Probabilities of Higher Arrest Rates"</span>,</span>
<span id="cb110-16"><a href="#cb110-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Cell (i,j) shows P(pi_i &gt; pi_j)"</span>,</span>
<span id="cb110-17"><a href="#cb110-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"District j"</span>,</span>
<span id="cb110-18"><a href="#cb110-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"District i"</span>,</span>
<span id="cb110-19"><a href="#cb110-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Probability"</span></span>
<span id="cb110-20"><a href="#cb110-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb110-21"><a href="#cb110-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb110-22"><a href="#cb110-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb110-23"><a href="#cb110-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)</span>
<span id="cb110-24"><a href="#cb110-24" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chicago_motor_theft_report_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From this heatmap we can see that there are several districts with pairwise probability of higher arrest rates being above 0.95. It is clear that the posterior distributions of arrest rates for motor vehicle thefts differ by district.</p>
<p>##Sources Cited</p>
<p>Bishop, Lindsay. “Vehicle Theft Statistics by State — and Most Stolen Cars and Motorcycles.” ValuePenguin, 25 Nov.&nbsp;2025, www.valuepenguin.com/motor-vehicle-theft-statistics.</p>
<p>Federal Bureau of Investigation. “National Incident-Based Reporting System (NIBRS) — Offense Categories and Data Tools.” FBI Crime Data Explorer, 2024, https://nibrs.fbi.gov/</p>
<p>Federal Bureau of Investigation. “FBI Releases Data on Motor Vehicle Theft: 2019–2023.” FBI News &amp; Press Releases, 17 Oct.&nbsp;2024, https://www.fbi.gov/news/press-releases/fbi-releases-motor-vehicle-theft-2019-2023</p>
<p>“Facts + Statistics: Auto Theft | III.” Iii.org, Insurance Information Institute, 2017, www.iii.org/fact-statistic/facts-statistics-auto-theft.&nbsp;Dr.&nbsp;Andrew Schiller. “Chicago, IL Crime Rates.” Neighborhoodscout.com, NeighborhoodScout, 24 Sept.&nbsp;2019, www.neighborhoodscout.com/il/chicago/crime.</p>
<p>“Monthly Auto Thefts, Last 5 Years | City of Chicago | Data Portal.” Cityofchicago.org, 2018, data.cityofchicago.org/Public-Safety/Monthly-Auto-Thefts-Last-5-Years/p6d7-vxbu.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>